# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\untitled.ui'
#
# Created by: PyQt6 UI code generator
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.controls = QtWidgets.QWidget(parent=self.centralwidget)
        self.controls.setObjectName("controls")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.controls)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.process = QtWidgets.QTextBrowser(parent=self.controls)
        self.process.setOpenExternalLinks(True)
        self.process.setOpenLinks(False)
        self.process.setObjectName("process")
        self.verticalLayout_2.addWidget(self.process)
        self.widget = QtWidgets.QWidget(parent=self.controls)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.continue_button = QtWidgets.QPushButton(parent=self.widget)
        self.continue_button.setObjectName("continue_button")
        self.horizontalLayout_2.addWidget(self.continue_button)
        self.change_key = QtWidgets.QPushButton(parent=self.widget)
        self.change_key.setEnabled(False)
        self.change_key.setObjectName("change_key")
        self.horizontalLayout_2.addWidget(self.change_key)
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout.addWidget(self.controls)
        self.view = QtWidgets.QWidget(parent=self.centralwidget)
        self.view.setObjectName("view")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.view)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.view)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.cipher = QtWidgets.QPlainTextEdit(parent=self.view)
        self.cipher.setObjectName("cipher")
        self.verticalLayout.addWidget(self.cipher)
        self.label_2 = QtWidgets.QLabel(parent=self.view)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.open_text = QtWidgets.QTextBrowser(parent=self.view)
        self.open_text.setObjectName("open_text")
        self.verticalLayout.addWidget(self.open_text)
        self.horizontalLayout.addWidget(self.view)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.continue_button.setText(_translate("MainWindow", "Следующий шаг"))
        self.change_key.setText(_translate("MainWindow", "Выбрать другой ключ"))
        self.label.setText(_translate("MainWindow", "Шифр:"))
        self.label_2.setText(_translate("MainWindow", "Результат расшифровки:"))